import { NgModule } from '@angular/core';
import {
  MatInputModule,
  MatProgressSpinnerModule,
  MatCardModule,
  MatButtonModule,
  MatToolbarModule,
  MatExpansionModule,
  MatPaginatorModule,
  MatDialogModule,
  MatIconModule,
  MatMenuModule,
  MatSidenavModule,
  MatRadioModule,
  MatListModule,
  MatTreeModule,
  MatAutocompleteModule,
  MatChipsModule,
  MatFormFieldModule,
  MatBottomSheetModule,
  MatVerticalStepper,
  MatStep,
  MatStepperModule,
  MatCheckboxModule,
  MatProgressBarModule
} from '@angular/material';

@NgModule({
  imports: [
    MatInputModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatButtonModule,
    MatToolbarModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatDialogModule,
    MatIconModule,
    MatMenuModule,
    MatSidenavModule,
    MatRadioModule,
    MatListModule,
    MatTreeModule,
    MatListModule,
    MatBottomSheetModule,
    MatStepperModule,
    MatCheckboxModule,
    MatProgressBarModule
  ],
  exports: [
    MatInputModule,
    MatProgressSpinnerModule,
    MatCardModule,
    MatButtonModule,
    MatToolbarModule,
    MatExpansionModule,
    MatPaginatorModule,
    MatDialogModule,
    MatIconModule,
    MatMenuModule,
    MatSidenavModule,
    MatRadioModule,
    MatListModule,
    MatTreeModule,
    MatListModule,
    MatAutocompleteModule,
    MatChipsModule,
    MatFormFieldModule,
    MatBottomSheetModule,
    MatStepperModule,
    MatCheckboxModule,
    MatProgressBarModule
  ]
})
export class AngularMaterialModule {}
